os: linux

language:
  - node_js

node_js:
  - "18"

dist: jammy #ubuntu 22.04

deploy: 
  - npm run deploy
 
script:
  - echo 0

stages:
  - name: deploy
    if: branch = main && type != pull_request

