os: linux

language:
  - node_js

node_js:
  - "18"

dist: jammy #ubuntu 22.04

script:
  - npm run predeploy
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: src/dist
  on:
    branch: gh-pages

stages:
  - name: deploy
    if: branch = main AND type != pull_request

